version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - redis
    networks:
      - app-network

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    
    ports:
      - "8501:8501"

    environment:
      - BACKEND_URL=http://app:8000

    networks:
      - app-network

    depends_on:
      - app

networks:
  app-network:
    driver: bridge